package io.icyfry.bitbucket.e2s.api.bot;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.hubspot.slack.client.models.response.SlackError;

import io.icyfry.bitbucket.e2s.api.Emoji2SlackException;

/**
 * Exception generated by the bot
 */
public class SlackBotException extends Emoji2SlackException {

    private static final long serialVersionUID = 1L;

    public SlackBotException(String message) {
        super(message);
    }

    public SlackBotException(Throwable cause) {
        super(cause);
    }

    public SlackBotException(String message, Throwable cause) {
        super(message, cause);
    }

    public SlackBotException(SlackError slackError) {
        super(slackError.getError());
	}

	@JsonProperty
    @Override
    public String getMessage() {
        return super.getMessage();
    }

    @JsonProperty
    @Override
    public String toString() {
        return super.toString();
    }
 
}