package io.icyfry.bitbucket.e2s.api;

/**
 * Exception generated by the plugin for security reasons
 */
public class Emoji2SlackSecurityException extends Emoji2SlackException {

    private static final long serialVersionUID = 1L;

    public Emoji2SlackSecurityException(String message) {
        super(message);
    }

    public Emoji2SlackSecurityException(Throwable cause) {
        super(cause);
    }

    public Emoji2SlackSecurityException(String message, Throwable cause) {
        super(message, cause);
    }
 
}