package io.icyfry.bitbucket.e2s.api;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Exception generated by the plugin
 */
public class Emoji2SlackException extends Exception {

    private static final long serialVersionUID = 1L;

    public Emoji2SlackException(String message) {
        super(message);
    }

    public Emoji2SlackException(Throwable cause) {
        super(cause);
    }

    public Emoji2SlackException(String message, Throwable cause) {
        super(message, cause);
    }

    @JsonProperty
    @Override
    public String getMessage() {
        return super.getMessage();
    }

    @JsonProperty
    @Override
    public String toString() {
        return super.toString();
    }
 
}