name: Java CI Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'
    - name: Deploy with Maven
      run: mvn -Dregistry=https://maven.pkg.github.com/icyfry -Dtoken={{ secrets.GITHUB_TOKEN }} --settings .github/workflows/settings.xml -B deploy --file pom.xml


